// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz3uS5fTn0kKexucWrXB7K8lxFJ7F8nNs',
    appId: '1:608480728221:web:0b0ecbdcbce2224200f074',
    messagingSenderId: '608480728221',
    projectId: 'iotapp-eb0e5',
    authDomain: 'iotapp-eb0e5.firebaseapp.com',
    storageBucket: 'iotapp-eb0e5.appspot.com',
    measurementId: 'G-QCNFVJ6P6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDvzyFMgsxBXkaxY0_esoPMqLXZondllU',
    appId: '1:608480728221:android:95db55a47201ea5f00f074',
    messagingSenderId: '608480728221',
    projectId: 'iotapp-eb0e5',
    storageBucket: 'iotapp-eb0e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVZPxN8zDkJxQydkH6x6p2gxsjGOQRtto',
    appId: '1:608480728221:ios:9f4d5ce828689a1900f074',
    messagingSenderId: '608480728221',
    projectId: 'iotapp-eb0e5',
    storageBucket: 'iotapp-eb0e5.appspot.com',
    iosBundleId: 'com.example.iot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVZPxN8zDkJxQydkH6x6p2gxsjGOQRtto',
    appId: '1:608480728221:ios:9f4d5ce828689a1900f074',
    messagingSenderId: '608480728221',
    projectId: 'iotapp-eb0e5',
    storageBucket: 'iotapp-eb0e5.appspot.com',
    iosBundleId: 'com.example.iot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz3uS5fTn0kKexucWrXB7K8lxFJ7F8nNs',
    appId: '1:608480728221:web:005f067642dfaeeb00f074',
    messagingSenderId: '608480728221',
    projectId: 'iotapp-eb0e5',
    authDomain: 'iotapp-eb0e5.firebaseapp.com',
    storageBucket: 'iotapp-eb0e5.appspot.com',
    measurementId: 'G-9XKK7P0Q3Q',
  );
}
